# title: Fabiano Chapuis
# logo: "/assets/img/headshot_circle_new.png" alt="300" style="width: 200px; height: 200px;"> #/assets/img/headshot_circle.png?raw=true
# description: I'm a passionate about Data Analysis, music and nature.
# show_downloads: false
# theme: jekyll-theme-minimal
google_analytics: G-D7SHH16JDS